// Generated by delombok at Mon Mar 13 21:37:03 MSK 2023
package com.lairon.plugins.xchat;

import java.util.UUID;

public class AbstractPlayer {
    private final UUID uuid;
    private final String name;

    @java.lang.SuppressWarnings("all")
    public AbstractPlayer(final UUID uuid, final String name) {
        this.uuid = uuid;
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public UUID getUuid() {
        return this.uuid;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AbstractPlayer)) return false;
        final AbstractPlayer other = (AbstractPlayer) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$uuid = this.getUuid();
        final java.lang.Object other$uuid = other.getUuid();
        if (this$uuid == null ? other$uuid != null : !this$uuid.equals(other$uuid)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AbstractPlayer;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $uuid = this.getUuid();
        result = result * PRIME + ($uuid == null ? 43 : $uuid.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AbstractPlayer(uuid=" + this.getUuid() + ", name=" + this.getName() + ")";
    }
}
