// Generated by delombok at Mon Mar 13 21:59:19 MSK 2023
package com.lairon.plugins.xchat.service;

import com.lairon.plugins.xchat.AbstractPlayer;
import com.lairon.plugins.xchat.adapter.BukkitAdapter;
import com.lairon.plugins.xchat.service.impl.placeholder.StrSubstitutorPlaceholderService;
import lombok.NonNull;
import me.clip.placeholderapi.PlaceholderAPI;
import org.bukkit.entity.Player;
import java.util.Map;

public class PapiPlaceholderService extends StrSubstitutorPlaceholderService {
    @Override
    public String setPlaceholders(@NonNull AbstractPlayer player, @NonNull String message, @NonNull Map<String, String> placeholders) {
        if (player == null) {
            throw new java.lang.NullPointerException("player is marked non-null but is null");
        }
        if (message == null) {
            throw new java.lang.NullPointerException("message is marked non-null but is null");
        }
        if (placeholders == null) {
            throw new java.lang.NullPointerException("placeholders is marked non-null but is null");
        }
        message = super.setPlaceholders(player, message, placeholders);
        Player bukkitPlayer = BukkitAdapter.adapt(player);
        if (bukkitPlayer != null) {
            message = PlaceholderAPI.setPlaceholders(bukkitPlayer, message);
        }
        return message;
    }
}
