// Generated by delombok at Mon Mar 13 21:37:04 MSK 2023
package com.lairon.plugins.xchat.service.impl.placeholder;

import com.lairon.plugins.xchat.AbstractPlayer;
import lombok.NonNull;
import org.apache.commons.lang.text.StrLookup;
import org.apache.commons.lang.text.StrSubstitutor;
import java.util.Map;

public class StrSubstitutorPlaceholderService extends AbstractPlaceholderService {
    @Override
    public String setPlaceholders(@NonNull AbstractPlayer player, @NonNull String message, @NonNull Map<String, String> placeholders) {
        if (player == null) {
            throw new java.lang.NullPointerException("player is marked non-null but is null");
        }
        if (message == null) {
            throw new java.lang.NullPointerException("message is marked non-null but is null");
        }
        if (placeholders == null) {
            throw new java.lang.NullPointerException("placeholders is marked non-null but is null");
        }
        StrSubstitutor sub = new StrSubstitutor(placeholders, "{", "}");
        sub.setVariableResolver(StrLookup.mapLookup(placeholders));
        return sub.replace(message);
    }
}
