// Generated by delombok at Mon Mar 13 21:59:19 MSK 2023
package com.lairon.plugins.xchat.listener;

import com.lairon.plugins.xchat.AbstractPlayer;
import com.lairon.plugins.xchat.handler.ChatHandler;
import com.lairon.plugins.xchat.adapter.BukkitAdapter;
import io.papermc.paper.event.player.AsyncChatEvent;
import net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

public class ChatListener implements Listener {
    private final ChatHandler chatHandler;

    @EventHandler(ignoreCancelled = true)
    public void onAsyncChat(AsyncChatEvent event) {
        AbstractPlayer player = BukkitAdapter.adapt(event.getPlayer());
        String message = LegacyComponentSerializer.legacyAmpersand().serialize(event.message());
        if (player == null || message == null) return;
        event.setCancelled(true);
        chatHandler.handleChat(player, message);
    }

    @java.lang.SuppressWarnings("all")
    public ChatListener(final ChatHandler chatHandler) {
        this.chatHandler = chatHandler;
    }
}
