name: xChat
version: '${project.version}'
main: com.lairon.plugins.xchat.ChatPlugin
api-version: 1.17
authors: [ 0xLairon1 ]
description: Chat system
softdepend:
  - PlaceholderAPI
commands:
  xChat:
    aliases:
      - chat