name: xChat
version: '${project.version}'
main: com.lairon.plugins.xchat.ChatPlugin
api-version: 1.17
authors: [ 0xLairon1 ]
description: Chat system
softdepend:
  - PlaceholderAPI
libraries:
  - me.minidigger:minimessage-text:2.0.3
  - net.kyori:text-adapter-bukkit:3.0.3