// Generated by delombok at Mon Mar 13 21:37:03 MSK 2023
package com.lairon.plugins.xchat.service.impl;

import com.lairon.plugins.xchat.Chat;
import com.lairon.plugins.xchat.service.ChatRegistryService;
import lombok.NonNull;
import java.util.ArrayList;
import java.util.List;

public class ArrayChatRegistryService implements ChatRegistryService {
    private final List<Chat> chats = new ArrayList<>();
    private Chat defaultChat;

    @Override
    public Chat getChat(char c) {
        return getChat(c, defaultChat);
    }

    @Override
    public Chat getChat(@NonNull String id) {
        if (id == null) {
            throw new java.lang.NullPointerException("id is marked non-null but is null");
        }
        return getChat(id, defaultChat);
    }

    @Override
    public Chat getChat(char c, Chat defaultChat) {
        return chats.stream().filter(chat -> chat.getSymbol() == c).findFirst().orElse(defaultChat);
    }

    @Override
    public Chat getChat(@NonNull String id, Chat defaultChat) {
        if (id == null) {
            throw new java.lang.NullPointerException("id is marked non-null but is null");
        }
        return chats.stream().filter(chat -> chat.getId().equalsIgnoreCase(id)).findFirst().orElse(defaultChat);
    }

    @Override
    public List<Chat> getChats() {
        List<Chat> list = new ArrayList<>(chats);
        if (defaultChat != null) list.add(defaultChat);
        return list;
    }

    @Override
    public void registerChat(@NonNull Chat chat) {
        if (chat == null) {
            throw new java.lang.NullPointerException("chat is marked non-null but is null");
        }
        if (getChat(chat.getId(), null) != null) throw new IllegalArgumentException("Chat " + chat.getId() + " is already registered");
        if (getChat(chat.getSymbol(), null) != null) throw new IllegalArgumentException("Chat with symbol " + chat.getSymbol() + " is already registered");
        chats.add(chat);
    }

    @Override
    public void clear() {
        chats.clear();
    }

    @Override
    public void unregisterChat(@NonNull Chat chat) {
        if (chat == null) {
            throw new java.lang.NullPointerException("chat is marked non-null but is null");
        }
        chats.remove(chat);
    }

    @java.lang.SuppressWarnings("all")
    public Chat getDefaultChat() {
        return this.defaultChat;
    }

    @java.lang.SuppressWarnings("all")
    public void setDefaultChat(final Chat defaultChat) {
        this.defaultChat = defaultChat;
    }
}
