// Generated by delombok at Mon Mar 13 21:37:04 MSK 2023
package com.lairon.plugins.xchat.service.impl;

import com.lairon.plugins.xchat.AbstractPlayer;
import com.lairon.plugins.xchat.Chat;
import com.lairon.plugins.xchat.service.PlaceholderService;
import com.lairon.plugins.xchat.service.PlayerService;
import com.lairon.plugins.xchat.service.SendChatService;
import lombok.NonNull;
import java.util.List;

public class DefaultSendChatService implements SendChatService {
    private final PlayerService playerService;
    private final PlaceholderService placeholderService;

    @Override
    public void sendOnChat(@NonNull AbstractPlayer player, @NonNull Chat chat, @NonNull String message) {
        if (player == null) {
            throw new java.lang.NullPointerException("player is marked non-null but is null");
        }
        if (chat == null) {
            throw new java.lang.NullPointerException("chat is marked non-null but is null");
        }
        if (message == null) {
            throw new java.lang.NullPointerException("message is marked non-null but is null");
        }
        List<AbstractPlayer> listeners = null;
        if (chat.getRange() < 0) {
            listeners = playerService.getOnlinePlayers();
        } else {
            listeners = playerService.getPlayersWithRange(player, chat.getRange());
        }
        message = placeholderService.setPlaceholders(player, chat.getFormat(), "message", message, "player", player.getName());
        for (AbstractPlayer listener : listeners) {
            playerService.sendMessage(listener, message);
        }
    }

    @java.lang.SuppressWarnings("all")
    public DefaultSendChatService(final PlayerService playerService, final PlaceholderService placeholderService) {
        this.playerService = playerService;
        this.placeholderService = placeholderService;
    }
}
