// Generated by delombok at Mon Mar 13 21:37:03 MSK 2023
package com.lairon.plugins.xchat.handler.impl;

import com.lairon.plugins.xchat.AbstractPlayer;
import com.lairon.plugins.xchat.Chat;
import com.lairon.plugins.xchat.config.LangConfig;
import com.lairon.plugins.xchat.handler.ChatHandler;
import com.lairon.plugins.xchat.service.ChatRegistryService;
import com.lairon.plugins.xchat.service.PlayerService;
import com.lairon.plugins.xchat.service.SendChatService;
import lombok.NonNull;

public class DefaultChatHandler implements ChatHandler {
    private final SendChatService sendChatService;
    private final PlayerService playerService;
    private final ChatRegistryService chatService;
    private final LangConfig lang;

    public void handleChat(@NonNull AbstractPlayer player, @NonNull String message) {
        if (player == null) {
            throw new java.lang.NullPointerException("player is marked non-null but is null");
        }
        if (message == null) {
            throw new java.lang.NullPointerException("message is marked non-null but is null");
        }
        if (message.isBlank()) {
            playerService.sendMessage(player, lang.yourMessageIsEmpty());
            return;
        }
        char c = message.charAt(0);
        Chat chat = chatService.getChat(c);
        if (chat == null) {
            playerService.sendMessage(player, lang.chatNotFound());
            return;
        }
        message = message.substring(1);
        sendChatService.sendOnChat(player, chat, message);
    }

    @java.lang.SuppressWarnings("all")
    public DefaultChatHandler(final SendChatService sendChatService, final PlayerService playerService, final ChatRegistryService chatService, final LangConfig lang) {
        this.sendChatService = sendChatService;
        this.playerService = playerService;
        this.chatService = chatService;
        this.lang = lang;
    }
}
